### ISSUE TITLE
Select_best_answer_spec error

### ISSUE THREAD

**Issue by groting** [groting/QnA_Project#7]
Не проходит часть теста: https://github.com/groting/QnA_Project/blob/master/spec/acceptance/select_best_answer_spec.rb 

    scenario 'Author tries to choose the best answer', js: true do
      within "#answer-#{question.answers.last.id}" do
        click_on 'The best' 
        expect(page).to have_content 'The best answer'
      end

      within(first(".answers-list li")) do
        expect(page).to have_content "AnswerText#{question.answers.last.id}"
      end
    end

Выводит что не находит текст 'AnswerText20' в ответе. Within(first(".answers-list li")) как видно из трейса возвращает ответ с телом 'AnswerText29' который является лучшим.  

Самое странное что тест не проходит при общем acceptance тестирование, если запустить этот тест отдельно он проходит, что значит на него влияют другие тесты. 

Долго пытался поправить, пока успехи не очень.

**Comment by vkurennov** [comment]
Разобрался. У тебя в фабриках тело ответа генерится через sequence. Каждый новый ответ, который был сгенерирован (не обязательно он сохраняет его в базе) увеличивает счетчик на 1, но эта последовательность - это не id в базе, это простой счетчик.
Когда ты запускаешь один тест, то у тебя id и этот счетчик совпадают, но когда запускаешь все тесты, то они перестают совпадать. Т.е. id ты можешь использовать в селекторах, а когда проверяешь текст ответа, надо использовать `body`

Вот правильный тест:
```

scenario 'Author tries to choose the best answer', js: true do
      within "#answer-#{question.answers.last.id}" do
        click_on 'The best' 
        expect(page).to have_content 'The best answer'
      end

      within(first(".answers-list li")) do
        expect(page).to have_content question.answers.last.body
      end
    end
```
